### ISSUE TITLE
Is $default_options really necessary?

### ISSUE THREAD

**Issue by bschonec** [joshbeard/puppet-login_defs#18]
Would it be better to eliminate the $default_options variable and assign all the values to $common_options and let hiera do the merging of the hashes?  I think it would make the heira code easier to read and would eliminate the need for the merge() function(s).

Preliminary code at #19

**Comment by joshbeard** [comment]
See if https://github.com/joshbeard/puppet-login_defs/pull/43 addresses this - it deprecates `common_options`, but does leave `default_options` so that the user can override or add a key/value using the `options` parameter without overriding all the other defaults.

**Comment by bschonec** [comment]
Works for me!  Thank you.
