### ISSUE TITLE
Travis build fail on Ruby < 2.0.0

### ISSUE THREAD

**Issue by Rocco83** [joshbeard/puppet-login_defs#3]
As by
https://travis-ci.org/joshbeard/puppet-login_defs/builds/189772745

Ruby version < 2.0.0 fails because of json_pure.
This is a dependency of puppet, and require ruby minimum version 2.0.0.
See http://stackoverflow.com/questions/38645491/vagrant-failing-to-install-puppet.

Possible way out:
- remove support for Ruby 1.9 and below
- stick max version for json_pure

I personally suggest to ignore old ruby revision, as this may be only the first package getting the issue, a lot more may come.
Ruby < 2.0.0 is out of security support from feb 2015
https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/ - even if of course distributions may keep the package version.

**Comment by joshbeard** [comment]
I apologize this issue was neglected for so long. With some recent activity on this module, I'm working on updating tests and hope to have this merged soon.

**Comment by joshbeard** [comment]
Replaced the travis tests with GitHub actions in #13
