### ISSUE TITLE
Remove RHEL5 and possibly RHEL6 support

### ISSUE THREAD

**Issue by bschonec** [joshbeard/puppet-login_defs#7]
RHEL5 is long since deprecated/unsupported.  RHEL6 is in extended support and probably should be removed.

**Comment by joshbeard** [comment]
I agree about RHEL5 but may hang on to RHEL6 for just a tad longer. I'm updating the module for current Puppet versions and practices as well as tests, so perhaps a major release could do include legacy OS removal or deprecation.

**Comment by joshbeard** [comment]
EL5 and EL6 were removed from the metadata as supported platforms, but I did leave the RedHat-6 defaults in place. This is in the "1.1.1" release on the forge. See https://github.com/joshbeard/puppet-login_defs/blob/master/CHANGELOG.md

I'll add a deprecation notice for EL6 in a future release.
